In [1]:
from torch import nn
import torch

from common import set_seed
from preprocess.process_data_sample import preprocess_bnci2014_001_sample
from naive_implement.shallow_convnet import ShallowConvNet

set_seed()
X, y = preprocess_bnci2014_001_sample(tmin=-0.5, tmax=4)
X = X[0:1,:,:]
X,X.shape

Choosing from all possible events
/opt/anaconda3/envs/ShallowConvNet/lib/python3.11/site-packages/moabb/datasets/preprocessing.py:278: UserWarning: warnEpochs <Epochs | 48 events (all good), 1.5 – 6 s (baseline off), ~9.1 MiB, data loaded,
 'left_hand': 12
 'right_hand': 12
 'feet': 12
 'tongue': 12>
  warn(f"warnEpochs {epochs}")
/opt/anaconda3/envs/ShallowConvNet/lib/python3.11/site-packages/moabb/datasets/preprocessing.py:278: UserWarning: warnEpochs <Epochs | 48 events (all good), 1.5 – 6 s (baseline off), ~9.1 MiB, data loaded,
 'left_hand': 12
 'right_hand': 12
 'feet': 12
 'tongue': 12>
  warn(f"warnEpochs {epochs}")
/opt/anaconda3/envs/ShallowConvNet/lib/python3.11/site-packages/moabb/datasets/preprocessing.py:278: UserWarning: warnEpochs <Epochs | 48 events (all good), 1.5 – 6 s (baseline off), ~9.1 MiB, data loaded,
 'left_hand': 12
 'right_hand': 12
 'feet': 12
 'tongue': 12>
  warn(f"warnEpochs {epochs}")
/opt/anaconda3/envs/ShallowConvNet/lib/python3.11/site-packages/moabb

(tensor([[[ 0.5051,  0.1656, -0.2651,  ..., -0.4802, -0.5219, -0.5698],
          [ 0.6479,  0.2506, -0.2819,  ..., -0.2637, -0.5338, -0.7528],
          [ 0.4502,  0.0364, -0.4540,  ..., -0.6055, -0.7902, -0.9222],
          ...,
          [ 0.3554, -0.0706, -0.4786,  ..., -0.6630, -1.0804, -1.3346],
          [ 0.5127,  0.0696, -0.3793,  ..., -0.5060, -0.8401, -1.0024],
          [ 0.2488, -0.1986, -0.5782,  ..., -0.3893, -0.7625, -0.9942]]]),
 torch.Size([1, 22, 1126]))

In [2]:
crop_size = 500
stride = 1

crops = []
for start in range(0, X.shape[2] - crop_size + 1, stride):
    crop = X[:, :, start:start + crop_size]  # (1, 22, 500)
    crops.append(crop)

crops = torch.cat(crops, dim=0)  # (627, 22, 500)
crops,crops.shape

(tensor([[[ 0.5051,  0.1656, -0.2651,  ...,  0.6631,  0.5315,  0.5489],
          [ 0.6479,  0.2506, -0.2819,  ...,  1.1466,  1.0986,  1.0867],
          [ 0.4502,  0.0364, -0.4540,  ...,  0.7665,  0.6321,  0.6241],
          ...,
          [ 0.3554, -0.0706, -0.4786,  ...,  1.0728,  1.0218,  0.8025],
          [ 0.5127,  0.0696, -0.3793,  ...,  0.8193,  0.9194,  0.8320],
          [ 0.2488, -0.1986, -0.5782,  ...,  0.8759,  0.8922,  0.7149]],
 
         [[ 0.1656, -0.2651, -0.5683,  ...,  0.5315,  0.5489,  0.6335],
          [ 0.2506, -0.2819, -0.6879,  ...,  1.0986,  1.0867,  1.0491],
          [ 0.0364, -0.4540, -0.7834,  ...,  0.6321,  0.6241,  0.6528],
          ...,
          [-0.0706, -0.4786, -0.6950,  ...,  1.0218,  0.8025,  0.4786],
          [ 0.0696, -0.3793, -0.6457,  ...,  0.9194,  0.8320,  0.6000],
          [-0.1986, -0.5782, -0.7614,  ...,  0.8922,  0.7149,  0.4178]],
 
         [[-0.2651, -0.5683, -0.5901,  ...,  0.5489,  0.6335,  0.7286],
          [-0.2819, -0.6879,

In [3]:
model = ShallowConvNet(X.shape) # X.shape not used
model.mean_pool = nn.Identity()
model.safe_log = nn.Identity()
model.dropout = nn.Identity()
model.final_conv = nn.Identity()
model.final_squeeze = nn.Identity()
model.eval()

logits = model(crops)

logits,logits.shape


(tensor([[[[3.7382e-02],
           [4.1538e-02],
           [6.2381e-02],
           ...,
           [3.5047e-02],
           [9.8300e-03],
           [4.7797e-06]],
 
          [[2.3882e-03],
           [1.3183e-02],
           [1.8901e-02],
           ...,
           [4.4192e-03],
           [4.1894e-04],
           [1.8507e-06]],
 
          [[6.1128e-04],
           [7.7381e-03],
           [2.9627e-02],
           ...,
           [1.1909e-01],
           [9.9768e-02],
           [6.3138e-02]],
 
          ...,
 
          [[5.6275e-03],
           [4.0875e-02],
           [9.0893e-02],
           ...,
           [3.0175e-01],
           [2.4430e-01],
           [1.7479e-01]],
 
          [[6.3578e-02],
           [8.6437e-02],
           [1.2350e-01],
           ...,
           [5.1423e-02],
           [3.2263e-02],
           [1.1945e-02]],
 
          [[5.8387e-03],
           [1.5256e-02],
           [4.1555e-02],
           ...,
           [1.0934e-01],
           [8.6041e-02

the recovered logits is same as the dense forward one

In [4]:
import torch

channels = logits.shape[1]
signal_length = 1102  # 原始长度

recovered = torch.zeros(1, channels, signal_length, 1)

for i in range(logits.shape[0]):
    recovered[:, :, i:i+476, :] = logits[i]

recovered,recovered.shape

(tensor([[[[3.7382e-02],
           [4.1538e-02],
           [6.2381e-02],
           ...,
           [5.9442e-04],
           [1.7480e-02],
           [5.4920e-02]],
 
          [[2.3882e-03],
           [1.3183e-02],
           [1.8901e-02],
           ...,
           [1.7211e-04],
           [3.2088e-02],
           [1.0386e-01]],
 
          [[6.1128e-04],
           [7.7381e-03],
           [2.9627e-02],
           ...,
           [1.2694e-04],
           [5.7105e-03],
           [1.1485e-02]],
 
          ...,
 
          [[5.6275e-03],
           [4.0875e-02],
           [9.0893e-02],
           ...,
           [1.2097e-02],
           [9.1894e-03],
           [4.2411e-03]],
 
          [[6.3578e-02],
           [8.6437e-02],
           [1.2350e-01],
           ...,
           [1.1332e-02],
           [1.8631e-03],
           [2.1949e-04]],
 
          [[5.8387e-03],
           [1.5256e-02],
           [4.1555e-02],
           ...,
           [5.4603e-02],
           [1.3113e-01

In [5]:
mean_pool = torch.nn.AvgPool2d(kernel_size=(75, 1), stride=(15, 1))
mean_pool_logits = mean_pool(logits)
mean_pool_logits,mean_pool_logits.shape

(tensor([[[[0.0539],
           [0.0462],
           [0.0522],
           ...,
           [0.0736],
           [0.0432],
           [0.0350]],
 
          [[0.0250],
           [0.0188],
           [0.0256],
           ...,
           [0.0334],
           [0.0276],
           [0.0214]],
 
          [[0.0407],
           [0.0323],
           [0.0599],
           ...,
           [0.0837],
           [0.0759],
           [0.0537]],
 
          ...,
 
          [[0.0596],
           [0.0465],
           [0.0677],
           ...,
           [0.0984],
           [0.0864],
           [0.0670]],
 
          [[0.0580],
           [0.0402],
           [0.0891],
           ...,
           [0.1266],
           [0.1133],
           [0.0869]],
 
          [[0.0444],
           [0.0551],
           [0.0537],
           ...,
           [0.0672],
           [0.0460],
           [0.0473]]],
 
 
         [[[0.0535],
           [0.0471],
           [0.0535],
           ...,
           [0.0734],
          

In [6]:
crop167 = mean_pool_logits[167]
crop167,crop167.shape

(tensor([[[0.1863],
          [0.1698],
          [0.1779],
          ...,
          [0.1369],
          [0.1340],
          [0.1356]],
 
         [[0.0319],
          [0.0329],
          [0.0227],
          ...,
          [0.0338],
          [0.0372],
          [0.0360]],
 
         [[0.2674],
          [0.2183],
          [0.2236],
          ...,
          [0.1244],
          [0.1209],
          [0.1255]],
 
         ...,
 
         [[0.3251],
          [0.2637],
          [0.2624],
          ...,
          [0.1335],
          [0.1315],
          [0.1321]],
 
         [[0.4992],
          [0.3846],
          [0.4030],
          ...,
          [0.1757],
          [0.1710],
          [0.1793]],
 
         [[0.0855],
          [0.0634],
          [0.0648],
          ...,
          [0.0660],
          [0.0636],
          [0.0637]]], grad_fn=<SelectBackward0>),
 torch.Size([40, 27, 1]))

In [7]:
log_logits = torch.log(torch.clamp(mean_pool_logits, min=1e-6))

log_logits,log_logits.shape

(tensor([[[[-2.9215],
           [-3.0742],
           [-2.9521],
           ...,
           [-2.6089],
           [-3.1425],
           [-3.3525]],
 
          [[-3.6894],
           [-3.9757],
           [-3.6649],
           ...,
           [-3.3995],
           [-3.5915],
           [-3.8422]],
 
          [[-3.2019],
           [-3.4338],
           [-2.8146],
           ...,
           [-2.4809],
           [-2.5782],
           [-2.9237]],
 
          ...,
 
          [[-2.8204],
           [-3.0679],
           [-2.6933],
           ...,
           [-2.3183],
           [-2.4487],
           [-2.7031]],
 
          [[-2.8474],
           [-3.2130],
           [-2.4184],
           ...,
           [-2.0668],
           [-2.1780],
           [-2.4427]],
 
          [[-3.1142],
           [-2.8988],
           [-2.9243],
           ...,
           [-2.6997],
           [-3.0798],
           [-3.0518]]],
 
 
         [[[-2.9280],
           [-3.0558],
           [-2.9281],
        

In [8]:
from torch.nn import init

conv_final = torch.nn.Conv2d(40, 4, (27, 1))
init.xavier_uniform_(conv_final.weight)
init.constant_(conv_final.bias, 0)
result = conv_final(log_logits)
result,result.shape

(tensor([[[[-3.4647]],
 
          [[-2.8334]],
 
          [[ 4.0701]],
 
          [[ 5.3102]]],
 
 
         [[[-3.4578]],
 
          [[-2.8334]],
 
          [[ 4.1346]],
 
          [[ 5.3082]]],
 
 
         [[[-3.4263]],
 
          [[-2.8145]],
 
          [[ 4.1733]],
 
          [[ 5.3260]]],
 
 
         ...,
 
 
         [[[-2.4209]],
 
          [[-1.9306]],
 
          [[ 4.3004]],
 
          [[ 5.7741]]],
 
 
         [[[-2.4617]],
 
          [[-1.9105]],
 
          [[ 4.2931]],
 
          [[ 5.7608]]],
 
 
         [[[-2.5054]],
 
          [[-1.8804]],
 
          [[ 4.2884]],
 
          [[ 5.7463]]]], grad_fn=<ConvolutionBackward0>),
 torch.Size([627, 4, 1, 1]))